{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.1.0.aar",
          "url": "sdk-ui-extensions-1.1.0.aar",
          "size": 570629,
          "sha512": "9203da2d3930b4244e5eab5ee16469e31471d01224e631eb544b67698343b04dbe11f58f549fe4c8ab284fa000713f3f4812bb85542832f3a304660063d0a52f",
          "sha256": "fa4ab78393d462e67edfe497db23882532991ed4ef1869db8a4e68976b668342",
          "sha1": "a4c7554d6887ecb46077e3ba7c65e19c478ace4a",
          "md5": "318cd0036fe28ec973371cd2de01727d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.7.1"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.1.0.aar",
          "url": "sdk-ui-extensions-1.1.0.aar",
          "size": 570629,
          "sha512": "9203da2d3930b4244e5eab5ee16469e31471d01224e631eb544b67698343b04dbe11f58f549fe4c8ab284fa000713f3f4812bb85542832f3a304660063d0a52f",
          "sha256": "fa4ab78393d462e67edfe497db23882532991ed4ef1869db8a4e68976b668342",
          "sha1": "a4c7554d6887ecb46077e3ba7c65e19c478ace4a",
          "md5": "318cd0036fe28ec973371cd2de01727d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-1.1.0-sources.jar",
          "url": "sdk-ui-extensions-1.1.0-sources.jar",
          "size": 50570,
          "sha512": "e7141655bfaf7f22d20f7a4ffde3e24478a8719ce4f40ddb4dbaf7ff3a20b7a5ad95f65e653db83d2c687f57ebbeab0055fd41e771eccd040737a0ad0f48a097",
          "sha256": "797ade6bceb1d4ddb891062c3670ecaca1158698a30a37143359281f7e7ae110",
          "sha1": "7f40507f8fbd1766fbe412efffa2042a9706e5a7",
          "md5": "41cbef2e9884a9bb8f95545876377f96"
        }
      ]
    }
  ]
}
