{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "1.0.0-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.0.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.0.0-snapshots.aar",
          "url": "sdk-ui-extensions-1.0.0-snapshots.aar",
          "size": 433629,
          "sha512": "7ebe1a5291d48cf6afd2bee0751d9d4cb4cd176592308cd43937765f122cbf453d2399c209d0d94202ebf17d6f3852a5176930e7e5d347fd84482209c67aa33b",
          "sha256": "92c8502bd3cad18bd7a60535677674a5fb8e82e64fc505155f8931a58919df1c",
          "sha1": "b893f4c037ed1e98227a5635c0cc067bc8cbf72a",
          "md5": "fa2972e087b5f3eb38e2633c44ec163e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.0.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.0.0-snapshots.aar",
          "url": "sdk-ui-extensions-1.0.0-snapshots.aar",
          "size": 433629,
          "sha512": "7ebe1a5291d48cf6afd2bee0751d9d4cb4cd176592308cd43937765f122cbf453d2399c209d0d94202ebf17d6f3852a5176930e7e5d347fd84482209c67aa33b",
          "sha256": "92c8502bd3cad18bd7a60535677674a5fb8e82e64fc505155f8931a58919df1c",
          "sha1": "b893f4c037ed1e98227a5635c0cc067bc8cbf72a",
          "md5": "fa2972e087b5f3eb38e2633c44ec163e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-1.0.0-snapshots-sources.jar",
          "url": "sdk-ui-extensions-1.0.0-snapshots-sources.jar",
          "size": 25451,
          "sha512": "35f96ed9ab01b0b7f5784e34e79c59f19ca802ba2361e18a5787b0801416f12424f5089c7c8c6deb32fc84e85f7afb6219e5b05c2cc7d2e99ab449ff5da4122e",
          "sha256": "a9b54fc389a22c288c1e2df6f946d2956f1f5cf55bf12561b6d31eb68ebefacf",
          "sha1": "0be5f02f1fd5495130cb5cbf11957a2c98e36059",
          "md5": "b95c6be1565828f32ade527f006f0305"
        }
      ]
    }
  ]
}
