{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "2.3.1.0-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "4.3.1.0-snapshots"
          }
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-cache-control",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-gif",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-2.3.1.0-snapshots.aar",
          "url": "sdk-ui-extensions-2.3.1.0-snapshots.aar",
          "size": 741717,
          "sha512": "78e70ba7f1a1ed315567b7c9d20c16bc6ad62841f61eb917db9837247b3a697508dad5a43fc71c6376c597a803733f0b68f64511ab536c43c7da259799aa67d7",
          "sha256": "a8f2d23016cc53b142f9c675fca079088105b231a976d08880b8e02879d226db",
          "sha1": "0f738cad16ed30a32fad965a937d70712fd8c9a1",
          "md5": "4fe0875d075b45a7436d376bf96f5777"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "4.3.1.0-snapshots"
          }
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "6.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-cache-control",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-gif",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-2.3.1.0-snapshots.aar",
          "url": "sdk-ui-extensions-2.3.1.0-snapshots.aar",
          "size": 741717,
          "sha512": "78e70ba7f1a1ed315567b7c9d20c16bc6ad62841f61eb917db9837247b3a697508dad5a43fc71c6376c597a803733f0b68f64511ab536c43c7da259799aa67d7",
          "sha256": "a8f2d23016cc53b142f9c675fca079088105b231a976d08880b8e02879d226db",
          "sha1": "0f738cad16ed30a32fad965a937d70712fd8c9a1",
          "md5": "4fe0875d075b45a7436d376bf96f5777"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-2.3.1.0-snapshots-sources.jar",
          "url": "sdk-ui-extensions-2.3.1.0-snapshots-sources.jar",
          "size": 85254,
          "sha512": "2acc1d9bb7cdccb8a74533a8c8ca4cbb685994de415bd6fceebc4665bb7fd7a06491f242fa4fe66c2435d85d535e4c5f469edf558ed3e330688a2f61761ef7e8",
          "sha256": "6910eab121f1832f13e8047e85d5d898725acca67debcb5da01df7ecc6d730ba",
          "sha1": "a5af9ccf90462165462f12b017f4399329117775",
          "md5": "d80997c0c61d1232136c2a56acb8ca49"
        }
      ]
    }
  ]
}
