{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "core-sdk",
    "version": "4.0.1.3-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "californium-core",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "scandium",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-sdk-4.0.1.3-snapshots.aar",
          "url": "core-sdk-4.0.1.3-snapshots.aar",
          "size": 2372950,
          "sha512": "30ffd042f8e15b7490ab91d3aa9b56fe913bb9324ef238ad83883d34a6e81c897b5b7d5194ec2a8c60a6d5a5095551fcd33357807da78b1dcc62e4727bd592fb",
          "sha256": "0931b24f6674656605137935a78fcaa749a9ce6a6a27cbf439e2c97bf7ea3917",
          "sha1": "3da604cac9879aca2f345c6b74790a6fd1609e8b",
          "md5": "cba54e171f3497c871e794f8e01409d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "californium-core",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "scandium",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-sdk-4.0.1.3-snapshots.aar",
          "url": "core-sdk-4.0.1.3-snapshots.aar",
          "size": 2372950,
          "sha512": "30ffd042f8e15b7490ab91d3aa9b56fe913bb9324ef238ad83883d34a6e81c897b5b7d5194ec2a8c60a6d5a5095551fcd33357807da78b1dcc62e4727bd592fb",
          "sha256": "0931b24f6674656605137935a78fcaa749a9ce6a6a27cbf439e2c97bf7ea3917",
          "sha1": "3da604cac9879aca2f345c6b74790a6fd1609e8b",
          "md5": "cba54e171f3497c871e794f8e01409d7"
        }
      ]
    }
  ]
}
