{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "2.0.2.9-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "4.0.1.4-snapshots"
          }
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "6.0.1.5-snapshots"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-cache-control",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-gif",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-2.0.2.9-snapshots.aar",
          "url": "sdk-ui-extensions-2.0.2.9-snapshots.aar",
          "size": 656312,
          "sha512": "3abab34a8bf6b859576d18911ccc4e6a1fbf6927e47bccf1deb23badeb5b2bb89209e134126679713f1f4f69f0653e48d62364ef6319d334b61241a2cfa4ea9e",
          "sha256": "d0db1fff0abe08c8a5eba3cfcb4c383f58ed7f04094437f3421b4835e77e78c0",
          "sha1": "448e0b5c09e878365b3a984a6dceaef147e432ea",
          "md5": "b8110c3fcd738cbe10496c1ea41bdb2e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "4.0.1.4-snapshots"
          }
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "6.0.1.5-snapshots"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-svg",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-cache-control",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-gif",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-2.0.2.9-snapshots.aar",
          "url": "sdk-ui-extensions-2.0.2.9-snapshots.aar",
          "size": 656312,
          "sha512": "3abab34a8bf6b859576d18911ccc4e6a1fbf6927e47bccf1deb23badeb5b2bb89209e134126679713f1f4f69f0653e48d62364ef6319d334b61241a2cfa4ea9e",
          "sha256": "d0db1fff0abe08c8a5eba3cfcb4c383f58ed7f04094437f3421b4835e77e78c0",
          "sha1": "448e0b5c09e878365b3a984a6dceaef147e432ea",
          "md5": "b8110c3fcd738cbe10496c1ea41bdb2e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-2.0.2.9-snapshots-sources.jar",
          "url": "sdk-ui-extensions-2.0.2.9-snapshots-sources.jar",
          "size": 72135,
          "sha512": "7102a3de9fc1c26aefa15b51614535c7d7c5d55d5949bffd1a36c7a6c43c935e89713c5c6af97a91fdb4f03dae2e4f09472f9eb0f6dbf578bb43bf5aa2ef6ad5",
          "sha256": "c21f934f3528120ec5985d319a048e1fd9b5cb0522c95fe892ee3ff457ded199",
          "sha1": "fa3383a5a9ba61eb7b73fe0b5093760ad5faf3b2",
          "md5": "085d9c3bfebceb705536d494e96813dc"
        }
      ]
    }
  ]
}
