{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "core-sdk",
    "version": "4.0.1.1-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "californium-core",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "scandium",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-sdk-4.0.1.1-snapshots.aar",
          "url": "core-sdk-4.0.1.1-snapshots.aar",
          "size": 2374594,
          "sha512": "628f87d129e2b3442338e713cee76841abfafc42072fa848edcc195130ba3c7f5f46ccff8e08f2e6acfad6c514b2e5f10e37e08453348b3b33a631ed78ecbe41",
          "sha256": "6c4d39315baff5eb4a2baf9b5e827ad71c6a66c1631726d80f80ad324a42580e",
          "sha1": "5655c57739bd274c274aa8f480bb4400fc256313",
          "md5": "e2cd2cf1c8c86f1e018200e5a3d33023"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "californium-core",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.eclipse.californium",
          "module": "scandium",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-sdk-4.0.1.1-snapshots.aar",
          "url": "core-sdk-4.0.1.1-snapshots.aar",
          "size": 2374594,
          "sha512": "628f87d129e2b3442338e713cee76841abfafc42072fa848edcc195130ba3c7f5f46ccff8e08f2e6acfad6c514b2e5f10e37e08453348b3b33a631ed78ecbe41",
          "sha256": "6c4d39315baff5eb4a2baf9b5e827ad71c6a66c1631726d80f80ad324a42580e",
          "sha1": "5655c57739bd274c274aa8f480bb4400fc256313",
          "md5": "e2cd2cf1c8c86f1e018200e5a3d33023"
        }
      ]
    }
  ]
}
