{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-routing",
    "version": "2.1.6.6-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "2.1.4.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-routing-2.1.6.6-snapshots.aar",
          "url": "sdk-routing-2.1.6.6-snapshots.aar",
          "size": 348142,
          "sha512": "039c0a6597a5e4e435208aa38c03c01bb9635b3047313ab0665ad5d4468f5e844625de606b7f91a416e5ec6ebf87585547858897dda0a4c12650fe52058ec29f",
          "sha256": "e847a6e33746b82a92b44b220f7d5ffd958cc9828392a5888cacef79b5482321",
          "sha1": "7fd25a2d8b5acdfd87e600665d5de0522fb73f79",
          "md5": "bde3672682d1829ac63bf9992d2a18cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "2.1.4.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-routing-2.1.6.6-snapshots.aar",
          "url": "sdk-routing-2.1.6.6-snapshots.aar",
          "size": 348142,
          "sha512": "039c0a6597a5e4e435208aa38c03c01bb9635b3047313ab0665ad5d4468f5e844625de606b7f91a416e5ec6ebf87585547858897dda0a4c12650fe52058ec29f",
          "sha256": "e847a6e33746b82a92b44b220f7d5ffd958cc9828392a5888cacef79b5482321",
          "sha1": "7fd25a2d8b5acdfd87e600665d5de0522fb73f79",
          "md5": "bde3672682d1829ac63bf9992d2a18cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-routing-2.1.6.6-snapshots-sources.jar",
          "url": "sdk-routing-2.1.6.6-snapshots-sources.jar",
          "size": 57526,
          "sha512": "ff0246fb6a1f957307188b0b7a1e1341fbfa66c3c73f3276ff39fbd2a9ff789f8242a957cbd2fd51e32c7a513f378e0c09f0faeaff0ea4aefb74b1d11873cb2d",
          "sha256": "a1f9d2022b36ef13464986b95968a52161a093240823cd8cfb3a96e592d77fbb",
          "sha1": "ef35bd30e3f4086e90878462898766c61582f319",
          "md5": "a273686c617fa64a3d281653d7e09a03"
        }
      ]
    }
  ]
}
