{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "1.2.3.2-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.2.4.3-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.2.5.3-snapshots"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.2.3.2-snapshots.aar",
          "url": "sdk-ui-extensions-1.2.3.2-snapshots.aar",
          "size": 652855,
          "sha512": "8ca8b13dffabb1125ed863f287751b6c6cf65ce26b330c1a769b1d807dac218386b77cec845f5d79ae08f16749a0ce846eedd37d6c320282fd0bdf5772e51b4f",
          "sha256": "f1df32888f389f2f61204e27592d9ae099dab6300cc9edb66179cfe221cb3bb3",
          "sha1": "b5e4ac1b5b75f3b7511ff23cef9874ffaeacfbae",
          "md5": "a10ae7f130dadf1f3932b03c8e17b1bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.7.1"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.2.4.3-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.2.5.3-snapshots"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.2.3.2-snapshots.aar",
          "url": "sdk-ui-extensions-1.2.3.2-snapshots.aar",
          "size": 652855,
          "sha512": "8ca8b13dffabb1125ed863f287751b6c6cf65ce26b330c1a769b1d807dac218386b77cec845f5d79ae08f16749a0ce846eedd37d6c320282fd0bdf5772e51b4f",
          "sha256": "f1df32888f389f2f61204e27592d9ae099dab6300cc9edb66179cfe221cb3bb3",
          "sha1": "b5e4ac1b5b75f3b7511ff23cef9874ffaeacfbae",
          "md5": "a10ae7f130dadf1f3932b03c8e17b1bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-1.2.3.2-snapshots-sources.jar",
          "url": "sdk-ui-extensions-1.2.3.2-snapshots-sources.jar",
          "size": 61743,
          "sha512": "5c90c70f1ebd2f7f5f665cde7c21322043e20f599d152a4939580ee899e60363ac5562e996fdbd3be0429f70a4b2f55ea8ba12631e220c756b2b01eb5748846f",
          "sha256": "334718ff8df0beeee4730b34b6b991e1f12e28b8ae5f4c2f72567f94cae2cb04",
          "sha1": "292ec46dc5958a7f9a17163917d24b99b4e4fbaa",
          "md5": "45b1c7513dcf8640bb61aff9db686a46"
        }
      ]
    }
  ]
}
