{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "remote-template-ui",
    "version": "1.0.0.4-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.0.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "remote-template-ui-1.0.0.4-snapshots.aar",
          "url": "remote-template-ui-1.0.0.4-snapshots.aar",
          "size": 432017,
          "sha512": "ebeeb90194ed6848e80d1d59d40087ac70d80e6a30af07f658bd3303b2922626d9316f5cd154ea364a8d19e0360de390a18eb3d9b0d97a0b61751dd9d89680aa",
          "sha256": "a90dfe106fba6f673f0e675477e0c5e6944571e163d140d95217909d76063508",
          "sha1": "7f93064b28f2ff1c41a9cbd8c5de563fd9a38301",
          "md5": "4c96f334f321fea059cd27bbdcdbfe91"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.0.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "remote-template-ui-1.0.0.4-snapshots.aar",
          "url": "remote-template-ui-1.0.0.4-snapshots.aar",
          "size": 432017,
          "sha512": "ebeeb90194ed6848e80d1d59d40087ac70d80e6a30af07f658bd3303b2922626d9316f5cd154ea364a8d19e0360de390a18eb3d9b0d97a0b61751dd9d89680aa",
          "sha256": "a90dfe106fba6f673f0e675477e0c5e6944571e163d140d95217909d76063508",
          "sha1": "7f93064b28f2ff1c41a9cbd8c5de563fd9a38301",
          "md5": "4c96f334f321fea059cd27bbdcdbfe91"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-template-ui-1.0.0.4-snapshots-sources.jar",
          "url": "remote-template-ui-1.0.0.4-snapshots-sources.jar",
          "size": 25414,
          "sha512": "ed5fc993b5e506216fb4e0c77529d416f7443ba20f146d175ceb67f099e1241629fcd9c4f8331383bab35863ef9d6169772c064f9d4b25aad0e04c3f3692771e",
          "sha256": "bf6073af3a8142e4b057b1a4692c4813f732249feb5db5cb624209cb7e3525fb",
          "sha1": "fb6f602d334c6a8b55edcf0a1639fd0c952d056c",
          "md5": "8f803ef7d150c3ff84091aab622421e9"
        }
      ]
    }
  ]
}
