{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui",
    "version": "6.2.0.0-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "sdk-routing",
          "version": {
            "requires": "6.2.0.0-snapshots"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.30.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "strictly": "6.2.0",
            "requires": "6.2.0",
            "prefers": "6.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-6.2.0.0-snapshots.aar",
          "url": "sdk-ui-6.2.0.0-snapshots.aar",
          "size": 3834857,
          "sha512": "654ba70a54f9d5a44ff6b31f9f3714280c0c95c9d52b111c177706ec2b742b3032a91a5193b20bf58bacd331140ede11fd4c3f649e689ba63931594de9901eee",
          "sha256": "a359f194dc2bf2af5eea5688386f69d2c7b859e50c0e8e68f6d5408d5227beb3",
          "sha1": "6533950aa73c705e898f77094dad701574c3fb6c",
          "md5": "4e7945d570d5f6c61339e16703885ab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "ai.nami",
          "module": "sdk-routing",
          "version": {
            "requires": "6.2.0.0-snapshots"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.30.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "strictly": "6.2.0",
            "requires": "6.2.0",
            "prefers": "6.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-6.2.0.0-snapshots.aar",
          "url": "sdk-ui-6.2.0.0-snapshots.aar",
          "size": 3834857,
          "sha512": "654ba70a54f9d5a44ff6b31f9f3714280c0c95c9d52b111c177706ec2b742b3032a91a5193b20bf58bacd331140ede11fd4c3f649e689ba63931594de9901eee",
          "sha256": "a359f194dc2bf2af5eea5688386f69d2c7b859e50c0e8e68f6d5408d5227beb3",
          "sha1": "6533950aa73c705e898f77094dad701574c3fb6c",
          "md5": "4e7945d570d5f6c61339e16703885ab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-6.2.0.0-snapshots-sources.jar",
          "url": "sdk-ui-6.2.0.0-snapshots-sources.jar",
          "size": 125585,
          "sha512": "6db93076a14fda4e89c8d0daca4aeb64fa9ebe2a3cdd873f3455a2932bef4f86617e48ff86999645371d46bbf1e43b0538ff45d16f59ef15a5b1016dd2b9f5d7",
          "sha256": "e2c049f4a88089750e958d1d28cf6f69a55f629a558437da75c76a506b9b3fdf",
          "sha1": "848de5d150148b4320e4f3f603ba8580ac5770d3",
          "md5": "73356dd6a390731f88769ef298cfb6c0"
        }
      ]
    }
  ]
}
