{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "remote-template-ui",
    "version": "1.0.0-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.0.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "remote-template-ui-1.0.0-snapshots.aar",
          "url": "remote-template-ui-1.0.0-snapshots.aar",
          "size": 357464,
          "sha512": "5b706a0e905089b77143cf30887df526fd53a98d55053b9e72a37917caacfae67f9edd058b37b0678182e7f0072d2780ae358e84939ea7c41a4a74acd512dabc",
          "sha256": "73e54915e9117de41990f14bf4f93d5b43fa6c1b35d7788362fc33e15e3d6612",
          "sha1": "82bcd3edb5834738616f8e7bb24ac3f0c731f9b0",
          "md5": "969fa092a3118480e8297a6326f374b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.0.4-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "remote-template-ui-1.0.0-snapshots.aar",
          "url": "remote-template-ui-1.0.0-snapshots.aar",
          "size": 357464,
          "sha512": "5b706a0e905089b77143cf30887df526fd53a98d55053b9e72a37917caacfae67f9edd058b37b0678182e7f0072d2780ae358e84939ea7c41a4a74acd512dabc",
          "sha256": "73e54915e9117de41990f14bf4f93d5b43fa6c1b35d7788362fc33e15e3d6612",
          "sha1": "82bcd3edb5834738616f8e7bb24ac3f0c731f9b0",
          "md5": "969fa092a3118480e8297a6326f374b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-template-ui-1.0.0-snapshots-sources.jar",
          "url": "remote-template-ui-1.0.0-snapshots-sources.jar",
          "size": 25275,
          "sha512": "a9163ee9a8ca470fc65d6aaf7d135b7db2c85c7424f2106c59c7593d2b0209829294485abae75bc4e7c65a12e00148ac8a62a2474fec030b5b7e13ff97e40b3e",
          "sha256": "d3299d48f6fdf70330f504fe141bb7e33d13de0a55805eb781e590e4f6b75738",
          "sha1": "9a92ed8eac0b9a58896ac9fa72670e73b278ef81",
          "md5": "85e2ba49a43eb73460fdbaa05344bc07"
        }
      ]
    }
  ]
}
