{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "2.0.0.24-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "4.0.0.9-snapshots"
          }
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "6.0.0.8-snapshots"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-2.0.0.24-snapshots.aar",
          "url": "sdk-ui-extensions-2.0.0.24-snapshots.aar",
          "size": 581154,
          "sha512": "cc56171cdbc55317f187bccade86a908e86f60dfcf11a8505c557e18bdc4d65dcbdd2cb71bd6c552c7ce087c4d39d59966d716137e6ea722c02b6cadb4445b6e",
          "sha256": "e9b0bac619c1afe7993a31e303e93b463bb163fdad0008e818235670f4630a91",
          "sha1": "5ae28d349b1bd287f7a6246df1f4bf11aec63589",
          "md5": "892541e3dc020abb98b68e5601d784ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "4.0.0.9-snapshots"
          }
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "6.0.0.8-snapshots"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.06.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.19.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-2.0.0.24-snapshots.aar",
          "url": "sdk-ui-extensions-2.0.0.24-snapshots.aar",
          "size": 581154,
          "sha512": "cc56171cdbc55317f187bccade86a908e86f60dfcf11a8505c557e18bdc4d65dcbdd2cb71bd6c552c7ce087c4d39d59966d716137e6ea722c02b6cadb4445b6e",
          "sha256": "e9b0bac619c1afe7993a31e303e93b463bb163fdad0008e818235670f4630a91",
          "sha1": "5ae28d349b1bd287f7a6246df1f4bf11aec63589",
          "md5": "892541e3dc020abb98b68e5601d784ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-2.0.0.24-snapshots-sources.jar",
          "url": "sdk-ui-extensions-2.0.0.24-snapshots-sources.jar",
          "size": 59362,
          "sha512": "acf0d8cb7ff921980b650c39086318f4dbf4be4a516ca6940cc84e4fc248a71a53da120db025b0dc2c79e213d69097e474b90e7c7f74211c60e8a16520e4c5ad",
          "sha256": "d46f6d2d09e73fc6a021eef135a757139826566f9ff77f7bba4f70e17b445c3d",
          "sha1": "db9ae92d02365471dc6600727861bfc52df27b22",
          "md5": "8c341455b22dff95c59dcbfccda4c46a"
        }
      ]
    }
  ]
}
