{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-routing",
    "version": "2.3.0.6-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "2.3.0.0-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-routing-2.3.0.6-snapshots.aar",
          "url": "sdk-routing-2.3.0.6-snapshots.aar",
          "size": 329305,
          "sha512": "3e6b875df5a70595ff6d3a41b03c12318b60bd80eb5f7af36efec4588e42912bfe7a983792a037cdc4e6474d6183016752e883c83ff3c4253527a3923ce7c7cb",
          "sha256": "2aa37bb1aaf897b208797a8d15071b864893ae57d25ae13089e146935ceb8c7a",
          "sha1": "4e880553d4c839be4bf1bee44466d2dc2b8484aa",
          "md5": "a0f2adab01d22ff1db439f26f2a04911"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "2.3.0.0-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-threadnetwork",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-routing-2.3.0.6-snapshots.aar",
          "url": "sdk-routing-2.3.0.6-snapshots.aar",
          "size": 329305,
          "sha512": "3e6b875df5a70595ff6d3a41b03c12318b60bd80eb5f7af36efec4588e42912bfe7a983792a037cdc4e6474d6183016752e883c83ff3c4253527a3923ce7c7cb",
          "sha256": "2aa37bb1aaf897b208797a8d15071b864893ae57d25ae13089e146935ceb8c7a",
          "sha1": "4e880553d4c839be4bf1bee44466d2dc2b8484aa",
          "md5": "a0f2adab01d22ff1db439f26f2a04911"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-routing-2.3.0.6-snapshots-sources.jar",
          "url": "sdk-routing-2.3.0.6-snapshots-sources.jar",
          "size": 52210,
          "sha512": "fcbdcf13a36515917e5edc7843eebd0896aecfabdc04d349468269e48d3e80a2e0bdd0ded6c3ff042eb280409227ed9bc5c88abb8803ddd9385d44c0bf8cfed2",
          "sha256": "72649cd3fccf007e2ff8bf5f07b18b3769b34ce633f5c7dcc2242285323cc72c",
          "sha1": "d2e13f74715bf959637dc120fe36cee0a01e5686",
          "md5": "c618c7acb8e5d098127685b697fa3184"
        }
      ]
    }
  ]
}
