{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "1.1.1-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.1.0-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.1.0-snapshots"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.1.1-snapshots.aar",
          "url": "sdk-ui-extensions-1.1.1-snapshots.aar",
          "size": 570626,
          "sha512": "af145156e88a0273d757d6c490aff82a7423a694a086e889c7e4c4625fa8dfcacca5163c80cb8a963b329bd6153077e642763a478b2ac8210166b1dc676af009",
          "sha256": "48f6169b77d8519025ffe4eb0c445ec2d0f99bffb8b7eac5792ae0a7908a33d7",
          "sha1": "9fb5f9989d70f94cf050a5bd0d102e211b062556",
          "md5": "d319364dc7c4ee3309443571ad1a2c70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.7.1"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.1.0-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.1.0-snapshots"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.1.1-snapshots.aar",
          "url": "sdk-ui-extensions-1.1.1-snapshots.aar",
          "size": 570626,
          "sha512": "af145156e88a0273d757d6c490aff82a7423a694a086e889c7e4c4625fa8dfcacca5163c80cb8a963b329bd6153077e642763a478b2ac8210166b1dc676af009",
          "sha256": "48f6169b77d8519025ffe4eb0c445ec2d0f99bffb8b7eac5792ae0a7908a33d7",
          "sha1": "9fb5f9989d70f94cf050a5bd0d102e211b062556",
          "md5": "d319364dc7c4ee3309443571ad1a2c70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-1.1.1-snapshots-sources.jar",
          "url": "sdk-ui-extensions-1.1.1-snapshots-sources.jar",
          "size": 50569,
          "sha512": "32021ef8b9519f7365a35b9409c7ace52a8ddb30a2b12533c4225f3e0dabdea90b050bc3477591fee57068bd3a750d0e741578820ea3829106a1b0142809918e",
          "sha256": "d97ca5508604ae8e685dee793aea67355445ead52005c922c75d735d625782e3",
          "sha1": "eb2481aa160b7b68f8ae422c29e39d0ea89fefee",
          "md5": "2258f02a4037db10d91f76702e7c188a"
        }
      ]
    }
  ]
}
