{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.nami",
    "module": "sdk-ui-extensions",
    "version": "1.2.3.1-snapshots",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.2.4.1-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.2.5.1-snapshots"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.2.3.1-snapshots.aar",
          "url": "sdk-ui-extensions-1.2.3.1-snapshots.aar",
          "size": 652770,
          "sha512": "9d2c7619b467e3c6aa73ef48287fe708b64875b64ea46cb0440e2e5b28b2d39d7a8ca233d79ce388e51502d40ee106f7c5670fb183090062998b779f05d56781",
          "sha256": "582dc74f04a00282d7f323d6f5469d48aade72397e989990fca35b413751f0eb",
          "sha1": "380cbacd394aaca78482fd68aaf61f56942b7853",
          "md5": "f6a3ee93a8adf1d1f5f9975de27ad64d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.02.02"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.material",
          "module": "material"
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-compose",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.3"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-core",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-json",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "coil",
          "version": {
            "requires": "32.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "com.yandex.div",
          "module": "div-lottie",
          "version": {
            "requires": "32.7.1"
          }
        },
        {
          "group": "ai.nami",
          "module": "core-sdk",
          "version": {
            "requires": "3.2.4.1-snapshots"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nami-android-protobuf"
            },
            {
              "group": "*",
              "module": "nami-nsd"
            },
            {
              "group": "*",
              "module": "nami-local-comm"
            }
          ]
        },
        {
          "group": "ai.nami",
          "module": "sdk-ui",
          "version": {
            "requires": "5.2.5.1-snapshots"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-ui-extensions-1.2.3.1-snapshots.aar",
          "url": "sdk-ui-extensions-1.2.3.1-snapshots.aar",
          "size": 652770,
          "sha512": "9d2c7619b467e3c6aa73ef48287fe708b64875b64ea46cb0440e2e5b28b2d39d7a8ca233d79ce388e51502d40ee106f7c5670fb183090062998b779f05d56781",
          "sha256": "582dc74f04a00282d7f323d6f5469d48aade72397e989990fca35b413751f0eb",
          "sha1": "380cbacd394aaca78482fd68aaf61f56942b7853",
          "md5": "f6a3ee93a8adf1d1f5f9975de27ad64d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sdk-ui-extensions-1.2.3.1-snapshots-sources.jar",
          "url": "sdk-ui-extensions-1.2.3.1-snapshots-sources.jar",
          "size": 61708,
          "sha512": "c248e6b722823d2ec6ed43020100ee43a4129a55cd32694de96312ccccf1f5387f02601b1a73cbb192d944b70694a187cc2d46c105a8f61fab5572652f336234",
          "sha256": "2431b5ffdfcad3a9e10c479b5fac231f1ba8a3104ac608192f5c2d288b43bcdd",
          "sha1": "c0dbf032a1ba7d80413482dd8d97e8894d8aa4f1",
          "md5": "6bdc97408d704f1e56833964f012b5ec"
        }
      ]
    }
  ]
}
